create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'operator'
    check (role in ('owner', 'operator')),
  display_name text,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.admin_users is
  '관리자 계정과 권한. 인증 정보가 아닌 운영 권한만 저장한다.';
comment on column public.admin_users.role is
  'owner는 관리자 권한 관리 가능, operator는 일반 운영 업무 담당';

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

comment on table public.admin_audit_logs is
  '관리자 변경 작업의 감사 기록. 애플리케이션 서버에서만 추가한다.';

create index if not exists admin_audit_logs_created_at_idx
  on public.admin_audit_logs (created_at desc);
create index if not exists admin_audit_logs_actor_idx
  on public.admin_audit_logs (actor_user_id, created_at desc);

create or replace function public.is_admin(
  allowed_roles text[] default array['owner', 'operator']::text[]
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = (select auth.uid())
      and is_active = true
      and role = any(allowed_roles)
  );
$$;

comment on function public.is_admin(text[]) is
  '현재 로그인 사용자가 활성 관리자이며 허용된 역할인지 확인한다.';

revoke all on function public.is_admin(text[]) from public;
grant execute on function public.is_admin(text[]) to authenticated;

create or replace function public.set_admin_users_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists admin_users_set_updated_at on public.admin_users;
create trigger admin_users_set_updated_at
  before update on public.admin_users
  for each row execute function public.set_admin_users_updated_at();

alter table public.admin_users enable row level security;
alter table public.admin_audit_logs enable row level security;

revoke all on table public.admin_users from anon, authenticated;
revoke all on table public.admin_audit_logs from anon, authenticated;

grant select on table public.admin_users to authenticated;
grant select on table public.admin_audit_logs to authenticated;

drop policy if exists "Admins can view their own membership"
  on public.admin_users;
create policy "Admins can view their own membership"
  on public.admin_users
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Owners can view admin memberships"
  on public.admin_users;
create policy "Owners can view admin memberships"
  on public.admin_users
  for select
  to authenticated
  using (public.is_admin(array['owner']::text[]));

drop policy if exists "Owners can view admin audit logs"
  on public.admin_audit_logs;
create policy "Owners can view admin audit logs"
  on public.admin_audit_logs
  for select
  to authenticated
  using (public.is_admin(array['owner']::text[]));
